### ISSUE TITLE
案出し

### ISSUE THREAD

**Issue by RiTa-23** [RiTa-23/catapult_Phase02#1]

**Comment by RiTa-23** [comment]
えのっきーシューティング

**Comment by manaberyota** [comment]
野菜・果物などの食材が安くうっているスーパーの情報を取得できるアプリ
食事する店を決めてくれるアプリ

**Comment by philitan** [comment]
欠席理由のテンプレート的なアプリ
(簡単な情報入力だけで提出できる)

**Comment by KanataOkumura** [comment]
google-mapのインスタ機能追加

**Comment by RiTa-23** [comment]
自分が見た作品リスト
他人に作品リストをツイッター的な感覚で共有できる

**Comment by KanataOkumura** [comment]
英語とか漢字を定期的に復習するアプリ
