### ISSUE TITLE
テーブル設計

### ISSUE THREAD

**Issue by RiTa-23** [RiTa-23/catapult_Phase02#13]
ユーザーテーブル

アイテムテーブル
id
商品のカテゴリ（野菜、肉、果物...）
商品名 （人参、豚肉、いちご...）
商品の値段
お店
登録したユーザー
登録日時

ストアテーブル
id
お店
位置情報

**Comment by manaberyota** [comment]
アイテムテーブル→Price でModel　作成

**Comment by manaberyota** [comment]
ストアテーブル→StoreでModel作成　
位置情報のカラムをどのように設定すればいいのかがわからない
とりあえず$table->location();と書いておいた
